name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        ocaml-version: [4.14.3,5.4.1]
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-local-packages: bechamel.opam
      - run: opam pin add . -n
      - run: opam install bechamel --with-test -v
